version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /img/tinker.png
    destination: /var/www/html/img/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startup.sh
      timeout: 400
      runas: root
